keys:
  - &host_portuus age1lghtkhxlz2tc5j9cjm6ancvz4a0mkgevjw4e2mhfar7cr5atl50snr5rs4
  - &host_edge age194tp22lgh6uw3lcg2u0j9ylllfvs6anjk4ns7prhy8e08k20q3jq439e6c
  - &user_sid age19yeqvv28fgrtk6jsh3xyaf0lch86kna6rcz4dwe962yyyyevu30sx474xy
  - &user_steffen age1e8p35795htf7twrejyugpzw0qja2v33awcw76y4gp6acnxnkzq0s935t4t
creation_rules:
  - path_regex: hosts/portuus/secrets/secrets.yaml$
    key_groups:
    - age:
      - *user_sid
      - *user_steffen
      - *host_portuus
  - path_regex: hosts/edge/secrets/secrets.yaml$
    key_groups:
    - age:
      - *user_sid
      - *user_steffen
      - *host_edge
