keys:
  - &host_portuus age1lghtkhxlz2tc5j9cjm6ancvz4a0mkgevjw4e2mhfar7cr5atl50snr5rs4
  - &user_sid age19yeqvv28fgrtk6jsh3xyaf0lch86kna6rcz4dwe962yyyyevu30sx474xy
creation_rules:
  - path_regex: hosts/portuus/secrets.yaml$
    key_groups:
    - age:
      - *user_sid
      - *host_portuus
  - path_regex: users/sid/home/secrets/secrets.yaml$
    key_groups:
    - age:
      - *user_sid
