name: Flake Check

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  flake-check:
    runs-on: self-hosted

    env:
      NIXPKGS_ALLOW_UNFREE: 1

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix flake check --impure
